### ISSUE TITLE
RNA-seq input

### ISSUE THREAD

**Issue by whitleyo** [greenelab/TDM#1]
Hi,

I've gone through your tutorial and I am wondering about the nature of the exact expected RNA-seq input. For the TCGA dataset used in the tutorial, presumably dataset 1 from your paper (Thompson et al. 2016), I tried examining the data and got:

`head(tcga)[,1:5]`
```

       TCGA.BH.A1F8.11B.21R.A13Q.07 TCGA.A2.A0SW.01A.11R.A084.07 TCGA.C8.A273.01A.11R.A16F.07
ABCA1                     1601.7785                     975.2898                    1372.6265
ABCA3                      772.2318                    1665.4072                    6043.4081
ABCB6                      423.6431                     506.7032                    1056.7385
ABCB9                      155.9208                     224.6062                     657.9381
ABCC11                      27.5387                    3623.8839                      25.8102
ABCC5                      771.6581                     285.6112                    2078.0173
       TCGA.E9.A1N3.01A.12R.A157.07 TCGA.GM.A2DD.01A.11R.A180.07
ABCA1                      664.9101                     599.1883
ABCA3                     7212.7984                    1881.1954
ABCB6                      928.2867                     843.5469
ABCB9                      118.7821                     310.2890
ABCC11                    2202.9389                    2599.9262
ABCC5                      502.4247                     540.6469
```

This doesn't appear to be discrete count data, but I'm guessing it could be library size normalized values or RPKM values. When I assess the distribution of data, I get a right skewed distribution as would be expected for RNA-seq count data.

`hist(as.vector(as.matrix(tcga[tcga < 1000])))`

![image](https://user-images.githubusercontent.com/25909144/41783031-dc74b4cc-7609-11e8-9f58-c2ae6d03feb9.png)

Thanks!

**Comment by cgreene** [comment]
@jeffreyat : This has come up a few times via e-mail. What do you think about putting this info into the readme (maybe in a FAQ section)?

**Comment by jeffreyat** [comment]
The input should be count data, but in this case they are expected counts from RSEM, which are also fine. It might also make sense to adjust for library size, which we did not look at in the paper. Thanks for the question, I will add a FAQ section to the readme to address this.
