### ISSUE TITLE
Please update the package install method

### ISSUE THREAD

**Issue by chilampoon** [greenelab/TDM#4]
Hi, when I run the `tdm_transform` function, this error occurs

```
Error: With R version 3.5 or greater, install Bioconductor packages using BiocManager; see https://bioconductor.org/install
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
```
This is because the `load_it()` in `package_loader.R` is still using biocLite, please update it, thanks!

**Comment by cgreene** [comment]
Hi @chilampoon - if you have these packages already loaded does the error still occur?
> c("data.table", "binr", "scales")
